version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: docker-udemy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - docker-udemy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-udemy-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
#    ports:
#      - "3000:3000"
    networks:
      - docker-udemy-network

  api:
    build: ./api
    container_name: docker-udemy-api
    command: npm run start
    restart: unless-stopped
#    ports:
#      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://stepbystep.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-udemy-network

  auth:
    build: ./auth
    container_name: docker-udemy-auth
    command: npm run start
    restart: unless-stopped
#    ports:
#      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://stepbystep.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - docker-udemy-network

  api_db:
    image: mongo:latest
    container_name: docker-udemy-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - docker-udemy-network

  auth_db:
    image: mongo:latest
    container_name: docker-udemy-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - docker-udemy-network

volumes:
    mongodb_api:
    mongodb_auth:

networks:
  docker-udemy-network:
    driver: bridge